server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://154.217.234.121:4886/epay?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Jiang@@0305091200&
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: MavisPayHikariCP

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: "epay-admin-jwt-secret-key-change-this-in-production-must-be-at-least-256-bits-long"
  expiration: 86400000